### ISSUE TITLE
Add Timeout library

### ISSUE THREAD

**Issue by eojreyem** [scimusmn/arduino-base-old#5]
https://playground.arduino.cc/Code/SimpleTimer/
I've been using this timeout library with success. However, there's a slightly non-intuitive workaround for the most common way we use timeouts. (Postpone timeout every time a button is pushed). 

Aaron H also has a timeout library on Gdrive that does not seem to be as extensive.

**Comment by brandonwkipp** [comment]
Can you dig Aaron's library out for this issue? I'd like to see what he wrote.

**Comment by eojreyem** [comment]
This link should bring you to a shop shared file. It should be visible to all of SMM.
https://drive.google.com/drive/folders/1_Kji-wrUV37wysbOFTnPGaFlcIGUunUF?usp=sharing

**Comment by brandonwkipp** [comment]
Oh boy, look at all that code! Thanks @eojreyem

**Comment by brandonwkipp** [comment]
@eojreyem I added a new Timer library; it is very loosely based off of Aaron's. I didn't use much of his code, but I think this form may be easier to read. I added your requested `postpone` function and updated the docs.

When you get a chance, could you take a look and see if it meets your expectations? After I get your ok, I'll go ahead and close the issue.

**Comment by eojreyem** [comment]
You rock!  I'll take a look.  Maybe I can rewrite my Electrostatic Precipitator code to use it.

**Comment by eojreyem** [comment]
Started looking into this. 
I don't think the postpone function does what I need it to do. It seems that it adds time for each button press? Which can really accumulate with button mashers on the floor.

The action I'm looking for is more as follows:
I push a button, and it times out in 30 seconds.  If I push that button again within the initial 30 seconds, I'd want it to timeout 30 seconds from the last button press.

So this?

`    postponedDuration = timeElapsed + postponeAmount;`
instead of this
`    postponedDuration = postponedDuration + postponeAmount;`

Or should we make a new function  `resetDuration()`

**Comment by brandonwkipp** [comment]
Ah, I misunderstood. Want to add the new method and submit a pull request for it? I can do it if you don't have time.

**Comment by brandonwkipp** [comment]
@eojreyem filed a pull request to fixed the postpone method behavior and I tested it.
